"""empty message

Revision ID: a4dc2ff591ee
Revises: 08be13fb613a
Create Date: 2022-02-15 11:09:47.829567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dc2ff591ee'
down_revision = '08be13fb613a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('unit_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'unit_count')
    # ### end Alembic commands ###
