"""empty message

Revision ID: 0f43b8656a1f
Revises: c9cee1e1e2dd
Create Date: 2022-02-22 08:39:47.514500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f43b8656a1f'
down_revision = 'c9cee1e1e2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('battles_exercises_exercise_id_fkey', 'battles_exercises', type_='foreignkey')
    op.drop_constraint('battles_exercises_battle_id_fkey', 'battles_exercises', type_='foreignkey')
    op.create_foreign_key(None, 'battles_exercises', 'exercises', ['exercise_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'battles_exercises', 'battles', ['battle_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battles_exercises', type_='foreignkey')
    op.drop_constraint(None, 'battles_exercises', type_='foreignkey')
    op.create_foreign_key('battles_exercises_battle_id_fkey', 'battles_exercises', 'battles', ['battle_id'], ['id'])
    op.create_foreign_key('battles_exercises_exercise_id_fkey', 'battles_exercises', 'exercises', ['exercise_id'], ['id'])
    # ### end Alembic commands ###
